name: Backend Cloud Run Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
          project_id: ${{ vars.GCP_PROJECT_ID }}
      - name: Setup Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - name: Debug Environment Variables
        run: |
          echo "GCP_PROJECT_ID=${{ vars.GCP_PROJECT_ID }}"
          echo "GCR_REPO_NAME=${{ vars.GCR_REPO_NAME }}"  
      - name: Build
        env:
          IMAGE_NAME: backend
          PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
        run: |-
          docker build -t asia-northeast1-docker.pkg.dev/$PROJECT_ID/${{ vars.GCR_REPO_NAME }}/$IMAGE_NAME:latest -f Dockerfile .
          docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/${{ vars.GCR_REPO_NAME }}/$IMAGE_NAME:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy second-brain-backend \
              --image asia-northeast1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCR_REPO_NAME }}/backend:latest \
              --platform managed \
              --port=8080 \
              --region asia-northeast1 \
              --allow-unauthenticated \
              --set-env-vars "DB_URI=${{ secrets.DB_URI }},JWT_SECRET=${{secrets.JWT_SECRET}},JWT_EXPIRE=1d,COOKIE_EXPIRE=${{secrets.COOKIE_EXPIRE}},CLIENT_ID=${{secrets.CLIENT_ID}},SMPT_HOST=${{secrets.SMPT_HOST}},SMPT_PORT=${{secrets.SMPT_PORT}},SMPT_MAIL=${{secrets.SMPT_MAIL}},SMPT_PASSWORD=${{secrets.SMPT_PASSWORD}},SMPT_SLOT_MAIL=${{secrets.SMPT_SLOT_MAIL}},SMPT_SLOT_PASSWORD=${{secrets.SMPT_SLOT_PASSWORD}},CORS_ORIGIN=https://makes.mindmatrix.io/"